services:
  portfolio:
    build: .
    container_name: meu-portfolio-angular
    ports:
      - "8082:8082"
    volumes:
      - ./dist/portfolio:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - nginx_net
    restart: unless-stopped

networks:
  nginx_net:
    external: true
    name: nginx_net
