services:
  portfolio:
    build: .
    container_name: meu-portfolio-angular
    ports:
      - "8082:80"  # Mapeando a porta 8082 local para a porta 80 do Nginx no container
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - nginx_net
    restart: unless-stopped

networks:
  nginx_net:
    external: true
    name: nginx_net
